import localFont from "next/font/local";
import "./globals.css";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import EditorContextProvider from "@/context/editor-context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const yekan = localFont({
  src: "./fonts/Yekan.woff",
  variable: "--font-Yekan",
  weight: "100 200 400 500 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="fa" dir="rtl">
        <body
          className={`${yekan.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <EditorContextProvider>{children}</EditorContextProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
