import { auth } from "@/auth";
import { ThemeProvider } from "@/context/theme-provider";
import { StoreProvider } from "@/store/StoreProvider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import { geistMono, geistSans } from "./fonts/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  favicon: "/favicon.ico",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <StoreProvider>
        <html lang="fa" dir="rtl">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
            <Toaster />
          </body>
        </html>
      </StoreProvider>
    </SessionProvider>
  );
}
